### PR TITLE
fix signing reclaim escrow tx from dapp

### LINKED ISSUE #249: dapp can't request signing reclaim escrow through ext-utils
reportedly, this fails with

```
FRAME_SEND_TRANSFER not confirmed {error: 'Please enter a valid wallet address'}
```

due to the transaction body not having a .to field

### PR DESCRIPTION
**Pull request by pro-wh**
reclaim escrow has no 'to' field, so we need to add some logic not to check for it

fixes #249

### CODE REVIEW

File: src/background/service/ExtUtils.js [hunk 1]
```diff
@@ -102,7 +102,7 @@ oasisExt.ext.ready({
                 const handled = oasis.signature.visitMessage(
                     {
                         withChainContext:
-                            ({
+                            /** @type {oasis.consensus.SignatureMessageHandlersWithChainContext} */ ({
```
Comment (pro-wh) [inline src/background/service/ExtUtils.js:105]: these create new type errors, since we're checking in strict mode. oasis-sdk itself doesn't use strict mode, so I hadn't noticed. I filed https://github.com/oasisprotocol/oasis-sdk/pull/790 over there

File: src/popup/pages/SignTransaction/index.js [hunk 2]
```diff
@@ -82,22 +82,26 @@ class SignTransaction extends React.Component {
       return
     }
     if (params.recognizedConsensusTransactionMethod) {
+      if (methodNeedsTo(params.method)) {
       let toAddress = trimSpace(params.to)
```
Comment (lukaw3d) [inline src/popup/pages/SignTransaction/index.js:86]: indent

**Review by lukaw3d — APPROVED** [review]

File: src/background/service/ExtDappService.js [hunk 3]
```diff
@@ -164,11 +164,16 @@ class ExtDappService {
           return
         }
         if (params.recognizedConsensusTransactionMethod) {
-          if (params.to.length <= 0 || !addressValid(params.to)) {
+          let presentAndValid = (/** @type {string} */ param) => param.length > 0 && addressValid(param)
```
[the remark this answers is not in the document]
Comment (pro-wh) [reply src/background/service/ExtDappService.js:167]: oo and it even is a param :clap: 

let's go with that here

File: src/popup/pages/SignTransaction/index.js (hunk 2 above)
Comment (pro-wh) [reply src/popup/pages/SignTransaction/index.js:86]: oops thanks
